source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-imagemagick'
    gem 'ffi', '~> 1.16.3'
    gem 'eventmachine', '~> 1.2.7'
    gem 'http_parser.rb', '~> 0.8.0'
    gem 'racc', '~> 1.7.3'
    gem 'sassc', '~> 2.4.0'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'htmlcompressor'
    gem 'htmlbeautifier'
    gem 'uri', '~> 0.13.0'
end
